In [1]:
import numpy as np

array_2d = np.array([[1, 2], [3, 4]])
array_1d = np.array([5, 6])

concat_linhas = np.concatenate((array_2d, [array_1d]), axis=0)
print(concat_linhas)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
array_2d_2 = array_1d.reshape(2, -1)
concat_colunas = np.concatenate((array_2d, array_2d_2), axis=1)
print(concat_colunas)

[[1 2 5]
 [3 4 6]]
